name: Kittygramm workflow
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubunti-latest
    
    steps:
    - name: Копируем код проекта
      uses: actions/checkout@v3
    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.9
    - name: Обновляем pip, устанавливаем flake8 и flake8-isort, устанавливаем зависимости проекта
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0
    - name: Тесты flake8 
      run: python -m flake8 backend/ 